### ISSUE TITLE
Documentation TODO's

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#128]
## General info

- conda-forge has nice docs: https://conda-forge.org/docs

## Open questions

- [x] where to host the docs? kipoi.github.io
  - [x] which framework to use
    - needs to be in markdown 

### docs/contributing

- [x] 01_Getting_started.md @avsecz
  - Install, git-lfs, Fork the repo
  - Checkout your fork locally (Alternatively, add another remote to .kipoi/models)
  - Read x.md
  - Explore how models similar to yours did it
    - Run kipoi init or copy the similar model into a new directory
  - Edit the files
  - Kipoi test
  - Push & submit a pull-request
- [x] 02_Writing_model.yaml.md @krrome
- [x] 03_Writing_dataloader.yaml.md @krrome
- [x] 04_Writing_dataloader.py.md @avsecz
- [x] 05_Writing_model.py.md @krrome
- [x] 06_dumping_models_programatically.md @avsecz
  - point to some of the models that were deposited automatically
  - Notes:
	- add the script, ipynb to the root of the repository
      - use Makefile or Snakefile for dumping the models
    - write notes for building the repo to readme.md
    - use `template` directory
	- preventing code duplication:
      - use *relative* soft-links to prevent code duplication
      - use jinja templating

### docs/postprocessing

- [x] variant_effect_prediction.md - @krrome
  - Detailed description of variant effect prediction + what is needed in model.yaml and dataloader.yaml

### docs/using

- [x] 01_Getting_started.md - @avsecz
  - Install Kipoi, 
  - go to website, 
  - choose a model, 
  - check the required files,
  - copy the snippet, 
  - (install dependencies) 
  - run the prediction
- [x] 02_Variant_effect_prediction.md - @krrome
  - detailed description of variant effect prediction
- [x] 03_Model_sources.md @avsecz

### docs/use-cases

- [x] 01_benchmarking_models.ipynb - @jisraeli
  - simple pwm -> deepbind -> accessiblity + DNA model
  - TODO - analyze the model predictions?
- [x] 02_variant_effect_prediction.ipynb - @krrome
  - complementary to `using/02_Variant_effect_prediction.md`
- [x] 03_composing_models.ipynb - @avsecz
  - different scenarios
	- all in the same framework
      - pack to the model 
    - different frameworks
      - compatible dependencies
		- pack to the dataloader
      - incompatible dependencies
		- pipe with snakemake
           - How how to have one environment per snakemake rule
- [x] 04_contributing_models.ipynb - @avsecz
  - show the Iris example
  - show the genomics example?

### Other

- [x]  split the README.md code into shorted chunks @avsecz
