### ISSUE TITLE
Integrate plugins to Kipoi

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#309]
### User stories
- I want to list all the available plugins for Kipoi: `kipoi.list_plugins()`
   - this would return a dataframe with columns:
     - plugin (str)
     - url (str)
     - installed (bool)
     - cli (bool)
     - short description (str)
- i want to list the plugins from the CLI and see a tsv output of `kipoi.list_plugins()`
- after installing the plugin `pip install kipoi_veff` I want to be able to run:
  - `kipoi veff <veff commands>`
    - the available plugins should be listed in the help:
```
$ kipoi -h
# Main commands
  predict ...
...
# Plugin commands 
  veff      <short plugin description>
```
  - ? `from kipoi.plugins.veff import <veff functions>`]
- postprocessing yaml specification should be correctly parsed if the package is installed https://github.com/kipoi/models/blob/master/Basset/model.yaml#L46

## TODO

- `plugin.py` - module
  - [x] specify a global variable `PLUGINS` (list of dicts)
  - [x] `is_installed(plugin)` - returns True if the plugin is installed
  - [x] `list_installed()` - returns all installed plugin names
  - [x] implement `list_plugins()`
  - [x] implement `get_model_yaml_parser(plugin)`  - returns the Related class for parsing parts of `model.yaml`
  - [x] implement `get_dataloader_yaml_parser(plugin)`  - returns the Related class for parsing parts of `dataloader.yaml`
  - [x] implement `get_cli_fn(plugin)` - returns the command line interface function
- [x] individual plugins.
  - add to `__init__.py`
    - `ModelParser`
    - `DataloaderParser`
    - `cli_main`
- [x] include `list_plugins` to `kipoi`
- [x] add `list_plugins` to CLI
- [x] add yaml parsing to Related classes
- [x] add plugins to CLI
- [x] remove all the postprocessing code and tests
- [ ] keep only a major simple test for each plugin
