### ISSUE TITLE
Model composition as a DAG: snakemake + kipoi case-study

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#56]
We should show how one can use the kipoi CLI together with snakemake to create the following workflows:

![image](https://user-images.githubusercontent.com/10011161/33321713-f4de7d46-d446-11e7-8f74-b7c22f466c28.png)

## TODO

- [ ] create two simple models (they don't even have to be implemented in Keras). Just use dummy predict_on_batch
- [ ] write a snakemake file with intermediary files being hdf5 files
  - how to glue things together? i.e. were to specify the logic: "take A from file A.hdf5 and B from BC.hdf5"?
- [x] add dependency management to snakemake via http://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html
