### ISSUE TITLE
Clarify and add further description tags in `model.yaml:info`

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi#60]
We discussed yesterday with @gagneur about questions should be answered by the model contributor. We think the following 3 optional fields are most important
- `cite_as` - a link or a description how to cite the paper (say a doi link)
- `trained_on` - a link or a description of the training dataset
  - side thought: it would be really nice some day if the training/test datasets would have a unique identifier. For now, this is only rigorously possible with kaggle/dream challenges. 
- `training_procedure` - brief description about the training procedure for the `trained_on` dataset. 
- `license` - license of the model - defaults to MIT

Currently we have
```python
@related.immutable
class Info(RelatedConfigMixin):
    """Class holding information about the info component.
    Parses the info section in model.yaml:

    info:
      authors:
        - name: Ziga Avsec
      doc: RBP binding prediction
      name: rbp_eclip
      version: 0.1
    """
    authors = related.SequenceField(Author, repr=True)
    doc = related.StringField()
    name = related.StringField(required=False)  # TODO - deprecate
    version = related.StringField(default="0.1", required=False)
    tags = StrSequenceField(str, default=[], required=False)
```

## Open questions
- are there any other important questions we could ask the contributor?

## TODO

- [ ] agree on the fields
- [x] update `kipoi.components.Info`
- [x] add license, cite_as, trained_on and training_procedure to the table
- [x] update all the models and all the ipynbs (30min)
- [ ] update the field on the webpage
